# Generated by Django 3.1.1 on 2020-11-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_codigo', models.AutoField(db_column='codigo_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
