# Generated by Django 3.1.1 on 2020-11-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
