# Generated by Django 3.1.1 on 2020-11-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
